### ISSUE TITLE
Trouble with resource in patient-example.xml

### ISSUE THREAD

**Issue by plynchnlm** [fhir-formats/fhir-formats.github.io#7]
I was very glad to find this tool.  However, when I tried to convert the patient-example.xml file from the collection of test data at https://github.com/FHIR/fluentpath/blob/master/spec/tests.zip, the resulting JSON was missing one telecom entry and the contact information.

The file seems to be from DTSU2.  I don't know that makes a difference to your tool.

**Comment by vadi2** [comment]
It would, the tool is for STU3! Do you need DSTU2 support?

**Comment by plynchnlm** [comment]
There does not seem to be an STU3 version of patient-example.xml.  Anyway, I expect to be working with both DTSU2 (which I hear Apple is using) and STU3 (and of course R4 when that is out).

**Comment by plynchnlm** [comment]
I did not really mean to close the issue, but perhaps that is appropriate since it is a STU3 tool.

**Comment by vadi2** [comment]
Yep, Apple implements the Argonaut spec which is DSTU2 only.

I'm seeing DSTU2 stick around longer than expected, in part due to Argonaut  - so I'll look into adding multi-version support and DSTU2 back in.
